name: deploy-book

on:
  push:
    branches:
      - main

env:
  BASE_URL: /${{ github.event.repository.name }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-book:
    #if: github.actor == 'jagar2' && github.repository != 'jagar2/Fall_2024_MEM679_Data-Analysis-and-Machine-Learning-for-Science-and-Manufacturing'
    runs-on: self-hosted
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build the book
        run: |
          jupyter-book build ./jupyterbook

      # Upload artifact and copy to SMB share
      - name: Upload and Deploy
        run: |
          id
          SMBSHARE="/mnt/drexel_web/MEM679" &&
          JBPATH="./jupyterbook" &&
          cp -r $JBPATH/_build/html/* $SMBSHARE

